language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm i

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
