language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm i

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
